version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/apps/travis/build

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  ApplicationStart:
    - location: script/start.sh
      runas: root
      timeout: 60