version: '3'
volumes:
  oim-geoserver-data:

services:
  db:
    container_name: oim-db
    restart: always
    build:
      context: ./doc/docker/postgres
      dockerfile: Dockerfile
    volumes:
      - ./doc/database:/database
      - ./init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
    ports:
      - 15432:5432

  geoserver:
    container_name: oim-geoserver
    restart: always
    build:
      context: ./doc/docker/geoserver
      dockerfile: Dockerfile
    volumes:
      - oim-geoserver-data:/geoserver-data
    ports:
      - 18080:8080
  #rabbitmq:
